ekf_output_logger_node:
  ros__parameters:
    use_sim_time: true

    ekf_topic: /odometry/kf_gps_odom
    pseudo_topic: /odometry/gps_or_ann
    gps_topic: /odometry/gps_sim
    odom_topic: /bumperbot_controller/odom_noisy
    ann_topic: /odometry/ann
    kf_imu_topic: /odometry/kf_gps_imu
    complementary_topic: /odometry/kf_complementary

    log_path: ~/bumperbot_ws/src/ekf_output_log.csv
